// <auto-generated />

using System;
using System.Web;

namespace Replika.Web.StateManagement
{
    public class Cookie
    {
        public static void Keep(string cookieName, object value, DateTime expires)
        {
            HttpCookie cookie = new HttpCookie(cookieName);
            cookie.Value = value.ToString();
            cookie.Expires = expires;
            HttpContext.Current.Response.Cookies.Add(cookie);
        }

        public static HttpCookie Peek(string cookiename)
        {
            if (HttpContext.Current.Request.Cookies[cookiename] != null)
            {
                return HttpContext.Current.Request.Cookies[cookiename];
            }
            else
            {
                return null;
            }
        }

        public static void Clear(string key)
        {
            HttpContext.Current.Response.Cookies.Remove(key);
        }

        public static bool Exists(string key)
        {
            return HttpContext.Current.Response.Cookies[key] != null;
        }
    }
}